language: node_js
node_js:
- '7'
deploy:
  provider: heroku
  api_key:
    secure: gF5kcrsDI2sAzk1w5ZWirOr39cLJDAsAvslDLVrPhAXoFPOw0uvMGGpzV+IDVBUYKr4Vc5zB2XAynLvmKzFALBUlmWL/04SCdmayGdWvTkHeKJBmKuGwYr+UxseE4h4P6snYaU4CWfHt6dcl/ApVUSIT4KHZ3P5eIhYSyxjVu1wVNM0Clrk9BMGsNt9QPGkwJkUZTHY4dBkTEdYri5bNA8iVsUBLkN1o5JveGYaMKxhXeQQaTj5FTUh9vwWlYRO05cmzlpMtUPhc2FwuhhVANH0DLl+dH/pupC29pFQfmTpGbyNCP6OuBGUxnyoiUqRzFaE8chPkEJRuxKJ4m/IQLtvyuWaZKOS5HTNvshfrghZekoY7NarKLuXnyl6/oORxuhGYdeobh1EN3D7klKo1vQSKNIz4zMlWsqjlvGTodtOrEndxtw5dWX18TpGsNhavZydTSxq46lHzkMoqICdzwxI46huRPWYmB3e2LpbaoKtGkDxyVfUJxuH73vVa/GunV2CfeFjdC+wJ30xdPNpkHeZnQmKglq74r3mOPV9yhZIPZbDWzgxM2hYNUvwBDEYSZFT9TCvTNsHmp1t5T2wXxPslTEUjjuqiIpFGZXxzB2PfvmeaYHNKqzp71uO294nDFrmLphL7Ee44ntI6H5csAgZj9+az17815WYIszX5tLE=
  app: shrouded-shore-72116
  on:
    repo: dnunna/marvel-react-heroku
